### ISSUE TITLE
Using API Keys instead of Account credentials

### ISSUE THREAD

**Issue by ewenmic** [twilio-labs/twilio-firebase-extensions#19]
Validation fails when attempting to use Twilio Enterprise SID - causing function deploy to fail.

It appears that Twilio Enterprise SID's start with SK, where as regular Twilio account SID's start with AC (which the firebase extension form expects)

**Comment by philnash** [comment]
Hi @ewenmic,

I think you are referring to a [Twilio API Key and Secret](https://www.twilio.com/docs/iam/keys/api-key) in this case. 

While I normally recommend using API Keys and Secrets because they are easier to revoke than an account's Auth Token, I didn't add them as config for this extension yet. That is because the extension also receives status callback webhooks from Twilio to record the delivery status of the message in the collection. To ensure that a webhook came from Twilio, the extension [validates the request signature](https://www.twilio.com/docs/usage/security#validating-requests). To do this requires the account's Auth Token. So, we could configure the extension with an API Key and Secret, but we'd need the Auth Token anyway to ensure our webhooks are safe. (I actually have an [issue open to document why this is the case](https://github.com/twilio-labs/twilio-firebase-extensions/issues/12).)

Are you able to use the Account SID and Auth Token instead? Or would you want to use the extension without the status webhook or without verifying the signature of the status webhook?

**Comment by ewenmic** [comment]
Hey @philnash 

Yes, I am - sorry for the confusion. I was given the keys in a secure document without access to the console. I just created a separate test account, and I get the same string structure when generating an API Key for a specific project. 

Ideally, I would like to use the API Key instead of the Account Auth Token. We're only using Twilio for a few projects currently but if that grows into the future it isn't realistic to provide the account credentials to everyone - I don't think our security engineers would allow it.

I think the status events are nice to have, but not entirely essential for the project I'm working on... I think it would be fine to skip the signature verification so long as there's another check before updating the firestore document (maybe as simple as checking if the document currently exists - or another collection checking if the messageSid has been sent before from this project)

Although not ideal, the worst that could happen would be that our logging documents wouldn't have accurate data. 

What do you think?

**Comment by ewenmic** [comment]
Hey @philnash,

Hope you're having a great week. Do you happen to have any thoughts or updates on this issue?
