### ISSUE TITLE
Unable to install Twilio Send Message Firebase Extension

### ISSUE THREAD

**Issue by waldothedeveloper** [twilio-labs/twilio-firebase-extensions#64]
I've spent an entire weekend trying to figure this out and it keeps saying the same thing...

![image](https://user-images.githubusercontent.com/16472274/235325592-ab23b555-ce5e-422f-ab69-66fc65a413fa.png)

**Comment by waldothedeveloper** [comment]
This extension simply does NOT work. I just opened a brand new account with Firebase, a brand new project, setup everything from zero, put it on a blaze plan, bought a twilio number, got the credentials from twilio, followed the steps to install the application, and this doesn't work. 
Why is this firebase extension even in the market? 

I'm very frustrated with all this wasting of time, money and energy. 

![image](https://user-images.githubusercontent.com/16472274/235336699-2191c406-e50a-4589-b2dc-de90e8cd9416.png)

**Comment by druv5319** [comment]
Hey Waldo, sorry to see you're running into this issue. Be default, the maxScale value should be 100: https://cloud.google.com/run/docs/configuring/max-instances#limits. However, for some reason you're limit is 41 as shown on the console logs. Looks like you're account may be having limited quotas for some reason. You may need to contact GCP support to see what the issue is on your environment.

**Comment by waldothedeveloper** [comment]
Hey @druv5319, thanks for getting back to me so quickly, I really appreciate it.
I have a question, so if my limis for some reason is 41, does this Twilio extensions requires a minimum limit of 100?

**Comment by druv5319** [comment]
Twilio extension does not have any limits for instances but what could be adding the limits is something on your environment or account.
