### ISSUE TITLE
Failed to upgrade extension with error unsupported region

### ISSUE THREAD

**Issue by ian-sayles** [twilio-labs/twilio-firebase-extensions#67]
During the upgrade from 0.2.1 to version 0.3.3 I get the following error:

failed to get channel for project  region europe-west2 channel ID firebase: unsupported region europe-west2

**Comment by druv5319** [comment]
Hey Ian, thanks for the notice. Ill look into this and get back to you within a few days.

**Comment by starry-park** [comment]
I have same issue since update the extestion.
"failed to get channel for project .... unsupported region australia-southeast1"
I tried several times uninstall and install again, and got same error.

**Comment by Tommertom** [comment]
`failed to get channel for project tscab-62ca5 region asia-south1 channel ID firebase: unsupported region asia-south1`

trying upgrade to 0.3.3

Had to uninstall (all functions from previous version were removed) - so production down 

Reinstall gives me error:

```
failed to create channel for project tscab-62ca5 region us-central1 channel ID firebase: [eventarc] CreateChannel projects/tscab-62ca5/locations/us-central1/channels/firebase failed: generic::failed_precondition: Creating channel requires enablement of service eventarcpublishing.googleapis.com. Enable it by visiting: https://console.developers.google.com/apis/api/eventarcpublishing.googleapis.com/overview?project=4nontisclosed
```

I manually enabled event-arc via Google Cloud Console

Uninstalled the extension 

Error installing - region Mumbai not supported.

Reverted to us-central1 (Iowa)

Now install works

Production down, nobody got hurt - but a working fallback would have been nice (maybe in general for Firebase Extensions)?

And when doing a repeat install of Extensions you suddenly get a bit ..... from all the clicks you need to do to get to the Twilio extension (please allow me this complaint).

**Comment by druv5319** [comment]
The latest version (0.3.3) uses EventArc to create a custom channel to listen for send-message events. Looks like its current supported regions are asia-northeast1, europe-west4, us-central1, and us-west1. If your application is not hosted on these regions, install the previous stable version (0.2.1) using the firebase CLI: `firebase ext:install twilio/send-message@0.2.1`.

In meantime, i'll look into workarounds and will push out an update soon.

**Comment by ian-sayles** [comment]
Thanks druv5319,  just checked on google about EventArc for never heard of it,  and it is supported on more regions than you listed:  https://cloud.google.com/eventarc/docs/locations

**Comment by starry-park** [comment]
I'm trying to reinstall and selected region is us-Central1 but still got error and can't install.

**Comment by Tommertom** [comment]
Reason to ditch Twilio

**Comment by Tommertom** [comment]
> `firebase ext:install twilio/send-message@0.2.1`

Can confirm this works indeed - also not forgetting to `firebase deploy --only extensions`

Thanks for the fallback.

**Comment by starry-park** [comment]
First, My english level is not that good and  I'm not a developer nor techniclal person, so my understanding is limited. 
Anyway what I gathered... Eventarc region is available for lots of regions and there are additional regions if you use Cloud Storage triggers or Firestore triggers.
Moreover, you can add a trigger (and channel) manually in Eventarc Trigger setting.
But as Twilio extension, Trigger Type is not a Goolge Source and it's Thirrd party, so you have to choose third party provider but Twilio is not listed. Only Datadog is listed as third party provider. Maybe it means that new version of Twilio extension is not officially supported by Google Cloud Platform as a pre-integrated provider. I'm not sure  but maybe that's why we can't install it???

**Comment by starry-park** [comment]
https://cloud.google.com/eventarc/docs/third-parties/third-parties-overview
In this article, it says ...
**Regionality**
All third-party events in Eventarc are regional. This means that every delivered third-party event is published to a channel connection, routed through a channel, and matched to a trigger, all in the same Google Cloud region.

However, the data regionality of third-party providers varies greatly, and Eventarc does not make any assertions about the regionality of event providers. The data location of a provider platform might not necessarily match that of the channel resource.

**Provider location**
Third-party providers are available only in supported Eventarc [locations](https://cloud.google.com/eventarc/docs/locations).

Providers might further limit available locations due to specific regionality requirements. See the provider-specific page for a list of supported regions in which they publish events.

Note that for this **Pre-GA feature,** the following locations are supported:

asia-northeast1
europe-west4
us-central1
us-west1
You cannot create a channel in any other location.

**Comment by druv5319** [comment]
Version 0.3.3 is now deprecated since installation was dependent on select Google Cloud regions that support Eventarc triggers. You can now update to the latest stable version (0.2.1) through the Firebase Console.
